const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { token: localStorage.getItem('attendly_token'), user: JSON.parse(localStorage.getItem('attendly_user') || 'null'), mode: 'WFO' };
const currentMonth = () => new Date().toISOString().slice(0, 7);
const holidayMonth = document.createElement('input'); holidayMonth.type = 'month'; holidayMonth.id = 'holiday-month'; holidayMonth.value = currentMonth(); holidayMonth.className = 'month-control';
const holidayMonthLabel = document.createElement('label'); holidayMonthLabel.className = 'holiday-month-picker'; holidayMonthLabel.textContent = 'Public holidays for'; holidayMonthLabel.appendChild(holidayMonth); document.querySelector('#leaves-list').before(holidayMonthLabel);
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Request failed'); return data; }
function showMessage(selector, value, good = false) { const node = $(selector); node.textContent = value; node.style.color = good ? '#218e3c' : ''; }
function initials(name) { return name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase(); }
function safe(value) { return String(value || '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
const dayType = document.createElement('select'); dayType.id = 'day-type'; dayType.innerHTML = '<option value="full_day">Full day</option><option value="half_day">Half day</option>';
const dayTypeLabel = document.createElement('label'); dayTypeLabel.className = 'day-type-label'; dayTypeLabel.textContent = 'Attendance type'; dayTypeLabel.appendChild(dayType); document.querySelector('.mode-grid').after(dayTypeLabel);
const adminLogin = document.createElement('button'); adminLogin.type = 'button'; adminLogin.className = 'link-button'; adminLogin.textContent = 'Admin sign in'; document.querySelector('#auth-form').after(adminLogin);
adminLogin.addEventListener('click', () => { $('#register-fields').classList.add('is-hidden'); $('#auth-form').dataset.register = 'false'; $('#auth-form').dataset.admin = 'true'; $('#auth-submit').innerHTML = 'Admin sign in <b>↗</b>'; $('.auth-card h1').textContent = 'Administrator access'; $('.auth-card > p').textContent = 'Sign in to manage employee attendance.'; $('#auth-toggle').classList.add('is-hidden'); adminLogin.classList.add('is-hidden'); });
function showApp() { $('#auth-view').classList.add('is-hidden'); $('#app-view').classList.remove('is-hidden'); const name = state.user.name || 'Employee'; $('#header-title').textContent = `Hello, ${name.split(' ')[0]}`; $('#header-avatar').textContent = initials(name); $('#profile-avatar').textContent = initials(name); $('#profile-name').textContent = name; $('#profile-role').textContent = `Product Design · ${state.user.employee_code || 'EMP001'}`; $('#profile-id').textContent = state.user.employee_code || 'EMP001'; $('#attendance-date').textContent = new Date().toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'long' }); if (state.user.role === 'admin') addAdminTab(); loadHome(); }
function addAdminTab() { const nav = $('.bottom-nav'); if (nav.querySelector('[data-screen="admin"]')) return; const button = document.createElement('button'); button.dataset.screen = 'admin'; button.innerHTML = '<span>▣</span>Admin'; nav.appendChild(button); button.addEventListener('click', () => { $$('.bottom-nav button').forEach((item) => item.classList.remove('active')); button.classList.add('active'); $$('.screen').forEach((screen) => screen.classList.add('is-hidden')); let screen = $('#admin'); if (!screen) { screen = document.createElement('section'); screen.id = 'admin'; screen.className = 'screen'; screen.innerHTML = '<div class="screen-heading"><span class="kicker">CONTROL ROOM</span><h2>Admin dashboard</h2></div><div class="snapshot-grid" id="admin-stats"></div><div class="record-list" id="admin-mode-list"></div><h3 class="subheading">Today\'s employees</h3><div id="admin-employees" class="record-list"></div><h3 class="subheading">Leave decisions</h3><div id="admin-leaves" class="record-list"></div>'; $('.app-frame').insertBefore(screen, $('.bottom-nav')); } screen.classList.remove('is-hidden'); $('#header-kicker').textContent = 'ADMIN'; loadAdminDashboard(); }); }
$('#header-avatar').addEventListener('click', () => { $$('.bottom-nav button').forEach((item) => item.classList.toggle('active', item.dataset.screen === 'profile')); $$('.screen').forEach((screen) => screen.classList.add('is-hidden')); $('#profile').classList.remove('is-hidden'); $('#header-kicker').textContent = 'ACCOUNT'; });
async function loadAdminDashboard() { try { const [data, leavePage] = await Promise.all([api(`/api/admin/dashboard?month=${currentMonth()}`), api('/api/admin/leaves?limit=100')]); $('#admin-stats').innerHTML = [['Employees', data.employees.active], ['Present today', data.employees.presentToday], ['Absent today', data.employees.absentToday], ['Pending leaves', data.leaves.pending || 0]].map(([label, value]) => `<div class="small-stat"><strong>${value}</strong><small>${label}</small></div>`).join(''); $('#admin-mode-list').innerHTML = `<p class="muted">Work mode totals · Holidays this month: ${data.holidays}</p><div class="record"><div><p>WFO</p><small>${data.workModes.WFO || 0} records</small></div><div><p>WFH</p><small>${data.workModes.WFH || 0} records</small></div><div><p>Late</p><small>${data.lateArrivals} arrivals</small></div></div>`; $('#admin-employees').innerHTML = data.todayEmployees.map((employee) => `<div class="record"><div class="record-date">${initials(employee.name)}</div><div><p>${safe(employee.name)}</p><small>${employee.status === 'present' ? `Present · ${employee.login_time || '--:--'}${employee.logout_time ? ` → ${employee.logout_time}` : ''} · ${employee.work_mode || '-'}` : 'Absent today'}</small></div><span class="${employee.status === 'present' ? 'pill' : 'late-pill'}">${employee.status}</span></div>`).join('') || '<p class="muted">No employees found.</p>'; $('#admin-leaves').innerHTML = (leavePage.records || []).map((leave) => `<div class="record"><div><p>${safe(leave.name)}</p><small>${leave.start_date} – ${leave.end_date}<br>${safe(leave.reason)}</small></div><span class="pending-pill">${leave.status}</span>${leave.status === 'pending' ? `<button class="button green leave-decision" data-id="${leave.id}" data-status="approved">Approve</button><button class="button outline leave-decision" data-id="${leave.id}" data-status="unapproved">Reject</button>` : ''}</div>`).join('') || '<p class="muted">No leave requests.</p>'; $$('.leave-decision').forEach((button) => button.addEventListener('click', async () => { await api(`/api/admin/leaves/${button.dataset.id}`, { method: 'PATCH', body: JSON.stringify({ status: button.dataset.status }) }); loadAdminDashboard(); })); } catch (error) { const target = $('#admin-stats'); if (target) target.innerHTML = `<p class="muted">${error.message}</p>`; } }
function setAuthMode(register) { $('#register-fields').classList.toggle('is-hidden', !register); $('#auth-form').dataset.register = register; $('#auth-form').dataset.admin = 'false'; $('#auth-submit').innerHTML = register ? 'Create account <b>↗</b>' : 'Sign in <b>↗</b>'; $('#auth-toggle').textContent = register ? 'I already have an account' : 'Create an employee account'; $('.auth-card h1').textContent = register ? 'Join your workspace' : 'Welcome back'; $('.auth-card > p').textContent = register ? 'Create an employee account to get started.' : 'Sign in to your attendance workspace.'; adminLogin.classList.remove('is-hidden'); }
$('#auth-toggle').addEventListener('click', () => setAuthMode($('#auth-form').dataset.register !== 'true'));
$('#auth-form').addEventListener('submit', async (event) => { event.preventDefault(); const register = event.currentTarget.dataset.register === 'true'; const admin = event.currentTarget.dataset.admin === 'true'; const body = { email: $('#email').value, password: $('#password').value }; if (register) Object.assign(body, { name: $('#name').value, employeeCode: $('#employeeCode').value }); try { const result = await api(register ? '/api/auth/register' : admin ? '/api/auth/admin-login' : '/api/auth/login', { method: 'POST', body: JSON.stringify(body) }); state.token = result.token; state.user = result.user; localStorage.setItem('attendly_token', state.token); localStorage.setItem('attendly_user', JSON.stringify(state.user)); showApp(); } catch (error) { showMessage('#auth-message', error.message); } });
$$('.mode').forEach((button) => button.addEventListener('click', () => { $$('.mode').forEach((item) => item.classList.remove('active')); button.classList.add('active'); state.mode = button.dataset.mode; }));
async function loadHome() { try { const [summary, today] = await Promise.all([api(`/api/attendance/summary?month=${currentMonth()}`), api('/api/attendance/today')]); $('#percentage').textContent = `${summary.attendancePercentage}%`; $('#present-count').textContent = summary.presentDays; $('#leave-count').textContent = summary.approvedLeaves; $('#holiday-count').textContent = summary.holidays; const checkedIn = today.status === 'present'; $('#attendance-state').textContent = checkedIn ? "You're checked in" : "You're not checked in"; $('#login-time').textContent = today.login_time || '--:--'; $('#logout-time').textContent = today.logout_time || '--:--'; $('.check-mark').textContent = checkedIn ? '✓' : '!'; $('#check-in').style.display = checkedIn ? 'none' : 'block'; $('#check-out').style.display = checkedIn && !today.logout_time ? 'block' : 'none'; if (today.work_mode) { state.mode = today.work_mode; $$('.mode').forEach((item) => item.classList.toggle('active', item.dataset.mode === state.mode)); } } catch (error) { showMessage('#attendance-message', error.message); } }
$('#check-in').addEventListener('click', async () => { try { const result = await api('/api/attendance/check-in', { method: 'POST', body: JSON.stringify({ workMode: state.mode, dayType: $('#day-type').value, lateReason: $('#lateReason').value }) }); $('#login-time').textContent = result.login_time; $('#attendance-state').textContent = "You're checked in"; $('#check-in').style.display = 'none'; $('#check-out').style.display = 'block'; showMessage('#attendance-message', `${result.day_type === 'half_day' ? 'Half-day ' : ''}attendance recorded.`, true); } catch (error) { showMessage('#attendance-message', error.message); if (error.message.toLowerCase().includes('late')) $('#late-reason-wrap').classList.remove('is-hidden'); } });
$('#check-out').addEventListener('click', async () => { try { const result = await api('/api/attendance/check-out', { method: 'PATCH' }); $('#logout-time').textContent = result.logout_time; showMessage('#attendance-message', 'Logout time recorded.', true); } catch (error) { showMessage('#attendance-message', error.message); } });
async function loadHistory() { try { const rows = await api(`/api/attendance/history?month=${currentMonth()}`); $('#history-present').textContent = rows.filter((row) => row.status === 'present').length; $('#history-late').textContent = rows.filter((row) => row.is_late).length; $('#history-list').innerHTML = rows.length ? rows.map((row) => `<div class="record"><div class="record-date"><b>${new Date(row.attendance_date).getDate()}</b><small>${new Date(row.attendance_date).toLocaleString(undefined, { month: 'short' })}</small></div><div><p>${row.login_time || '--:--'} · ${row.work_mode || '-'}</p><small>${row.is_late ? `Late: ${safe(row.late_reason)}` : 'On time'}</small></div>${row.is_late ? '<span class="late-pill">Late</span>' : ''}</div>`).join('') : '<p class="muted">No daily records this month.</p>'; } catch (error) { $('#history-list').innerHTML = `<p class="muted">${error.message}</p>`; } }
async function loadLeaves() { try { const rows = await api('/api/leaves'); $('#leaves-list').innerHTML = rows.length ? rows.map((row) => `<div class="leave"><span class="leave-icon">▤</span><div class="leave-info"><b>Casual leave</b><small>${row.start_date} – ${row.end_date}</small></div><span class="pending-pill">${row.status}</span></div>`).join('') : '<p class="muted">No leave requests yet.</p>'; } catch (error) { $('#leaves-list').innerHTML = `<p class="muted">${error.message}</p>`; } }
async function loadHolidays() { try { const selectedMonth = $('#holiday-month').value || currentMonth(); const rows = await api(`/api/holidays?month=${selectedMonth}`); $('#leaves-list').innerHTML = `<div class="leave"><span class="leave-icon">▦</span><div class="leave-info"><b>${rows.length} public holidays</b><small>${new Date(`${selectedMonth}-01`).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</small></div></div>${rows.length ? rows.map((row) => `<div class="leave"><span class="leave-icon">✦</span><div class="leave-info"><b>${row.name}</b><small>${new Date(`${String(row.holiday_date).slice(0, 10)}T00:00:00`).toLocaleDateString(undefined, { weekday: 'short', day: 'numeric', month: 'short' })}</small></div></div>`).join('') : '<p class="muted">No public holidays recorded for this month.</p>'}`; } catch (error) { $('#leaves-list').innerHTML = `<p class="muted">${error.message}</p>`; } }
$$('.bottom-nav button').forEach((button) => button.addEventListener('click', () => { $$('.bottom-nav button').forEach((item) => item.classList.remove('active')); button.classList.add('active'); $$('.screen').forEach((screen) => screen.classList.add('is-hidden')); $(`#${button.dataset.screen}`).classList.remove('is-hidden'); $('#header-kicker').textContent = button.dataset.screen === 'home' ? 'TODAY' : button.textContent.toUpperCase(); if (button.dataset.screen === 'history') loadHistory(); if (button.dataset.screen === 'leaves') loadLeaves(); }));
$('#new-leave').addEventListener('click', () => $('#leave-dialog').showModal()); $('#leave-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await api('/api/leaves', { method: 'POST', body: JSON.stringify({ startDate: $('#leave-start').value, endDate: $('#leave-end').value, reason: $('#leave-reason').value }) }); $('#leave-dialog').close(); event.target.reset(); loadLeaves(); } catch (error) { showMessage('#leave-message', error.message); } });
$$('.tabs button').forEach((button, index) => button.addEventListener('click', () => { $$('.tabs button').forEach((item) => item.classList.remove('active')); button.classList.add('active'); if (index === 0) loadLeaves(); else loadHolidays(); }));
holidayMonth.addEventListener('change', loadHolidays);
function logout() { localStorage.clear(); location.reload(); } $('#logout').addEventListener('click', logout);
if (state.token && state.user) showApp();
