package com.attendly.employee;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.view.*; import android.widget.*; import org.json.*;

public class MainActivity extends Activity {
    private final int GREEN = Color.rgb(30, 107, 82), INK = Color.rgb(24, 34, 31), PAPER = Color.rgb(245, 248, 244), LIME = Color.rgb(217, 242, 98);
    private LinearLayout root, content; private TextView status, loginTime, logoutTime, percentage, summary; private EditText email, password, lateReason; private String mode = "WFO";
    private android.content.SharedPreferences preferences;
    private TextView text(String value, int size) { TextView view = new TextView(this); view.setText(value); view.setTextSize(size); view.setTextColor(INK); view.setPadding(0, 10, 0, 10); return view; }
    private Button button(String label) { Button button = new Button(this); button.setText(label); button.setTextColor(Color.WHITE); button.setBackgroundColor(GREEN); return button; }
    private EditText input(String hint, boolean secret) { EditText field = new EditText(this); field.setHint(hint); if (secret) field.setInputType(129); field.setPadding(18, 5, 18, 5); return field; }
    @Override public void onCreate(Bundle state) { super.onCreate(state); preferences = getSharedPreferences("attendly", MODE_PRIVATE); ApiClient.setToken(preferences.getString("token", null)); if (preferences.contains("token")) dashboard(); else login(); }
    private void base() { root = new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(28, 28, 28, 20); root.setBackgroundColor(PAPER); setContentView(root); }
    private void login() { base(); TextView logo = text("A", 34); logo.setTextColor(GREEN); root.addView(logo); root.addView(text("Welcome back", 30)); root.addView(text("Sign in to your attendance workspace.", 16)); email = input("Email", false); password = input("Password", true); root.addView(email); root.addView(password); Button submit = button("SIGN IN  ↗"); root.addView(submit); TextView message = text("", 14); root.addView(message); submit.setOnClickListener(view -> { JSONObject body = new JSONObject(); try { body.put("email", email.getText().toString()); body.put("password", password.getText().toString()); } catch (JSONException ignored) {} ApiClient.request("/api/auth/login", "POST", body, (data, error) -> { if (error != null) message.setText(error); else { preferences.edit().putString("token", data.optString("token")).putString("name", data.optJSONObject("user").optString("name")).apply(); ApiClient.setToken(data.optString("token")); dashboard(); } }); }); }
    private void dashboard() { base(); LinearLayout header = new LinearLayout(this); header.setOrientation(LinearLayout.HORIZONTAL); TextView title = text("Hello, " + preferences.getString("name", "Employee"), 25); header.addView(title, new LinearLayout.LayoutParams(0, -2, 1)); Button signout = button("Sign out"); header.addView(signout); root.addView(header); signout.setOnClickListener(view -> { preferences.edit().clear().apply(); ApiClient.setToken(null); login(); }); content = new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); ScrollView scroll = new ScrollView(this); scroll.addView(content); root.addView(scroll, new LinearLayout.LayoutParams(-1, 0, 1)); home(); LinearLayout nav = new LinearLayout(this); String[] labels = {"Home", "History", "Leave", "Profile"}; for (String label : labels) { Button item = new Button(this); item.setText(label); nav.addView(item, new LinearLayout.LayoutParams(0, -2, 1)); item.setOnClickListener(view -> { if (label.equals("Home")) home(); if (label.equals("History")) history(); if (label.equals("Leave")) leave(); if (label.equals("Profile")) profile(); }); } root.addView(nav); }
    private void home() { content.removeAllViews(); content.addView(text("ATTENDANCE STATUS", 12)); content.addView(text("You're checked in", 22)); content.addView(text("Wednesday, 23 September", 15)); LinearLayout times = new LinearLayout(this); loginTime = text("Login\n10:16", 17); logoutTime = text("Logout\n--:--", 17); times.addView(loginTime, new LinearLayout.LayoutParams(0, -2, 1)); times.addView(logoutTime, new LinearLayout.LayoutParams(0, -2, 1)); content.addView(times); content.addView(text("Work mode\nWhere are you working today?", 17)); LinearLayout modes = new LinearLayout(this); Button office = button("Office\nWFO"); Button home = button("Home\nWFH"); modes.addView(office, new LinearLayout.LayoutParams(0, -2, 1)); modes.addView(home, new LinearLayout.LayoutParams(0, -2, 1)); content.addView(modes); office.setOnClickListener(v -> mode = "WFO"); home.setOnClickListener(v -> mode = "WFH"); lateReason = input("Late login reason (required when late)", false); content.addView(lateReason); Button checkin = button("Check in"); Button checkout = button("Record logout time"); content.addView(checkin); content.addView(checkout); status = text("", 14); content.addView(status); checkin.setOnClickListener(v -> { JSONObject body = new JSONObject(); try { body.put("workMode", mode); body.put("lateReason", lateReason.getText().toString()); } catch (JSONException ignored) {} ApiClient.request("/api/attendance/check-in", "POST", body, (data, error) -> { if (error != null) status.setText(error); else { loginTime.setText("Login\n" + data.optString("login_time")); status.setText("Attendance recorded"); } }); }); checkout.setOnClickListener(v -> ApiClient.request("/api/attendance/check-out", "PATCH", null, (data, error) -> { if (error != null) status.setText(error); else logoutTime.setText("Logout\n" + data.optString("logout_time")); })); content.addView(text("Monthly snapshot\nYour month at a glance", 20)); percentage = text("0%  Attendance", 30); content.addView(percentage); summary = text("Present  0\nLeave  0\nHolidays  0", 16); content.addView(summary); ApiClient.request("/api/attendance/summary?month=2026-09", "GET", null, (data, error) -> { if (error == null) { percentage.setText(data.optString("attendancePercentage") + "%  Attendance"); summary.setText("Present  " + data.optInt("presentDays") + "\nLeave  " + data.optInt("approvedLeaves") + "\nHolidays  " + data.optInt("holidays")); } }); }
    private void history() { content.removeAllViews(); content.addView(text("YOUR RECORD\nAttendance history", 24)); ApiClient.request("/api/attendance/history?month=2026-09", "GET", null, (data, error) -> { if (error != null) { content.addView(text(error, 14)); return; } for (int i = 0; i < data.length(); i++) { JSONObject row = data.optJSONObject(i); content.addView(text(row.optString("attendance_date") + "\n" + row.optString("login_time") + " · " + row.optString("work_mode") + "\nLate: " + row.optString("late_reason", "-"), 16)); } }); }
    private void leave() { content.removeAllViews(); content.addView(text("TIME OFF\nLeave & holidays", 24)); Button apply = button("Apply for leave  +"); content.addView(apply); apply.setOnClickListener(v -> { Toast.makeText(this, "Use the web dashboard for the full leave form, or extend this screen with start/end date fields.", Toast.LENGTH_LONG).show(); }); ApiClient.request("/api/leaves", "GET", null, (data, error) -> { if (error == null) for (int i = 0; i < data.length(); i++) { JSONObject row = data.optJSONObject(i); content.addView(text(row.optString("start_date") + " - " + row.optString("end_date") + "\n" + row.optString("status"), 16)); } }); }
    private void profile() { content.removeAllViews(); content.addView(text("ACCOUNT\nYour profile", 24)); content.addView(text(preferences.getString("name", "Employee") + "\nEmployee\n\nEmployee ID\nAssigned by admin\n\nDaily start time\n09:15\n\nWorkplace\nWFO / WFH flexible", 18)); }
}
